In [1]:
a = 1
print(a)

1


In [2]:
b = "hello"
b

'hello'

In [4]:
import math
math.pi

3.141592653589793

# numpy

In [7]:
import numpy as np

In [8]:
listy = [1,2,3,4,5,6,7,8,9]
np.array(listy)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
list1 = [1,2,3]
list2 = [3,4,5]
list3 = [5,6,7]
arr2 = np.array([list1, list2, list3])

In [10]:
print(arr2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


# pandas

In [15]:
import pandas as pd

In [16]:
s = pd.Series(list1)
s

0    1
1    2
2    3
dtype: int64

In [17]:
s.index = [101, 102, 103]

In [18]:
s < 2

101     True
102    False
103    False
dtype: bool

In [19]:
s[0:2]

101    1
102    2
dtype: int64

In [21]:
s[s < 2]

101    1
dtype: int64

In [23]:
s.name = 'series'
s

101    1
102    2
103    3
Name: series, dtype: int64

In [24]:
s.index.name = "ID"
s

ID
101    1
102    2
103    3
Name: series, dtype: int64

In [26]:
s = pd.Series(np.random.random(4)*100, 
              index=["North", "East", "South", "West"], name = "Happiness Percentage")
s

North    31.267098
East     20.881615
South    94.683171
West     11.109834
Name: Happiness Percentage, dtype: float64

In [27]:
s.mean()

39.48542957142333

In [29]:
s.max()

94.68317132989907

In [31]:
s.idxmax()

'South'

In [32]:
s["Central"] = np.nan
s

North      31.267098
East       20.881615
South      94.683171
West       11.109834
Central          NaN
Name: Happiness Percentage, dtype: float64